### ISSUE TITLE
Wheels for Python 3.6

### ISSUE THREAD

**Issue by qdamian** [pymssql/pymssql#473] opened 2016-12-23 23:57 UTC
Hi,

It would be great if you can provide wheels for Python 3.6.

Thanks!

**Comment by markuman** [comment] 2017-01-09 16:34
Installing `2.2.0.dev0` works fine here using python 3.6.0 and pip 9.0.1
    `pip install git+https://github.com/pymssql/pymssql.git`

While installing latest release (`2.1.3`) with `pip install pymssql` failed.

**Comment by ktritz** [comment] 2017-02-01 04:29
Fails for me as well, Windows 10 x64, Python 3.6, pip 9.0.1
error:  Cannot open include file: 'sqlfront.h': No such file or directory

**Comment by zhehao** [comment] 2017-02-15 07:56
There is a ready-made wheel on [this page](http://www.lfd.uci.edu/~gohlke/pythonlibs/#pymssql), file `pymssql‑2.1.3‑cp36‑cp36m‑win_amd64.whl` is what you are looking for.

**Comment by mas-dse-juremigi** [comment] 2017-03-06 22:27
Unfortunately, wheels for linux on python 3.6 is not available. Also, I could not build the source using python 3.6

**Comment by ek-ok** [comment] 2017-03-20 19:31
Yeah same as [mas-dse-juremigi](https://github.com/mas-dse-juremigi). Wheels for linux on python 3.6 would be very nice.

**Comment by rsyring** [comment] 2017-06-22 11:51
The link above now has wheels for 3.6.

**Comment by KptainBiwouak** [comment] 2017-10-06 07:16
Thanks for the wheel but how to use it in replacement of standard setup: pip install?

**Comment by KptainBiwouak** [comment] 2017-10-08 20:20
I ve tried to install wheel pymssql‑2.1.3‑cp36‑cp36m‑win_amd64.whl but NOT successfully
Same issue : sqlfront.h NOT found

  Failed building wheel for pymssql
  Running setup.py clean for pymssql
Failed to build pymssql
Installing collected packages: pymssql
  Running setup.py install for pymssql ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/.gfmwk_tmp_061017075825_128/spectools/pip-build-xhn9bmej/pymssql/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /.gfmwk_tmp_061017075825_128/spectools/pip-hclx7ae8-record/install-record.txt --single-version-externally-managed --compile:
    setup.py: platform.system() => 'CYGWIN_NT-10.0'
    setup.py: platform.architecture() => ('64bit', 'WindowsPE')
    setup.py: platform.libc_ver() => ('', '')
    setup.py: Not using bundled FreeTDS
    setup.py: include_dirs = []
    setup.py: library_dirs = ['/usr/local/lib']
    running install
    running build
    running build_ext
    cythoning _mssql.pyx to _mssql.c
    warning: _mssql.pyx:143:4: Exception already a builtin Cython type
    building '_mssql' extension
    creating build
    creating build/temp.cygwin-2.9.0-x86_64-3.6
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/usr/src/ports/python3/python3-3.6.1-1.x86_64/build=/usr/src/debug/python3-3.6.1-1 -fdebug-prefix-map=/usr/src/ports/python3/python3-3.6.1-1.x86_64/src/Python-3.6.1=/usr/src/debug/python3-3.6.1-1 -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/usr/src/ports/python3/python3-3.6.1-1.x86_64/build=/usr/src/debug/python3-3.6.1-1 -fdebug-prefix-map=/usr/src/ports/python3/python3-3.6.1-1.x86_64/src/Python-3.6.1=/usr/src/debug/python3-3.6.1-1 -I/usr/include/python3.6m -c _mssql.c -o build/temp.cygwin-2.9.0-x86_64-3.6/_mssql.o -DMSDBLIB
    _mssql.c:435:22: fatal error: sqlfront.h: No such file or directory
     #include "sqlfront.h"
                          ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

**Comment by dondon2475848** [comment] 2017-10-18 08:30
try below code:
```
# Install pre-requesite packages
sudo apt-get install unixodbc unixodbc-dev freetds-dev freetds-bin tdsodbc
```

**Comment by KptainBiwouak** [comment] 2017-10-30 05:44
In fact  I need a  wheel for pymssql supporting:
- freetds 1.0.0
- python 3.6.1
- cygwin 2.9.0 (64bits)

By using pip3 With pymssql 2.1.3,  symbol DB_VERSION80 is not found

**Comment by jpgimenez** [comment] 2018-01-10 20:32
@KptainBiwouak look at my PR #522, I'm generating wheels with the latest FreeTDS and all python versions, https://ci.appveyor.com/project/jpgimenez/pymssql/build/89/job/89921w6b3numas98/artifacts

**Comment by DoctorLai** [comment] 2018-02-01 11:27
@dondon2475848   thanks.  Your solution works for me!

**Comment by fastviper** [comment] 2018-02-12 12:30
I've just tried pip install git+https://github.com/pymssql/pymssql.git
on my Windows 10, python 3.6.4-x64 and it fails exactly like 2.1.3 (missing sqlfront.h).

I don't think any config or wheels is to be corrected here. The problem is that one needs to have freeTDS library and headers installed before, which is next to impossible on Windows (no installer, only zipped freeTDS is available). 

As a side note: Anaconda distribution solved these problems and `conda install pymssql` just simply works (but you need a new root for that).

**Comment by cuishuang** [comment] 2018-02-22 07:20
brew unlink freetds
brew install freetds@0.91
brew link --force freetds@0.91
sudo pip install pymssql

**Comment by swb-tohear** [comment] 2018-02-23 10:35
Really ugly fix for this: in the error message for missing sqlfront.h you'll see a temp path, something like C:\Users\ADMINI~1\AppData\Local\Temp\3\pip-build-x199e3u9\pymssql\freetds\

download freedts from here https://github.com/ramiro/freetds/releases and rename the folder to "vs2016_64" then pop it into the pymssql/freedts folder that will appear in your temp while it's building.

**Comment by marioidival** [comment] 2018-08-02 18:36
Still failed to linux?

**Comment by AlexHagerman** [comment] 2018-08-28 19:10
3.6 wheels are available via pypi

**Closed by AlexHagerman** 2018-08-28 19:10 UTC

**Comment by facundofarias** [comment] 2019-02-17 08:54
Using the version 2.1.4 it solved the issue for me.
