### ISSUE TITLE
pymssql segmentation fault

### ISSUE THREAD

**Issue by pcdinh** [pymssql/pymssql#261] opened 2014-08-02 04:40 UTC
Hi,

I was reported that my server crashed many times lately on Ubuntu server. Core dump file was generated. After reading it with gdb, I found that pymssql crashed the server app when it tried to fetch results

+ python 2.7.6
+ Ubuntu 13.10 (Azure VM)
+ pymssql 2.1.1-dev 

```
gdb python CoreDump
```

```
(gdb) bt
#0  0x00007fd4a5f0ba8b in raise (sig=11) at ../nptl/sysdeps/unix/sysv/linux/pt-raise.c:38
#1  <signal handler called>
#2  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:31
#3  0x00007fd49fd6588d in __pyx_f_6_mssql_15MSSQLConnection_get_result (__pyx_v_self=0x3700980) at _mssql.c:12153
#4  0x00007fd49fd5c8cc in __pyx_f_6_mssql_15MSSQLConnection_execute_query (__pyx_v_self=0x3700980,
    __pyx_v_query_string='SELECT f.FileID,\n                              f.[Type],\n                              f.IsFolder,\n                             (CASE \n                                WHEN m.NewRelativePath IS NULL THEN f.LocalRelativePath \n                                ELSE m.NewRelativePath \n                              END) AS LocalRelativePath,\n                             (CASE \n                                WHEN m.NewFileName IS NULL THEN f.[FileName]\n                                ELSE m.NewFileName \n                              END) AS [FileName],\n                             (CASE \n                                WHEN m.NewFileSize IS NULL THEN f.FileSize \n                                ELSE m.NewFileSize \n                              END) AS FileSize,\n                             (CASE \n                                WHEN m.NewCheckSum IS NULL THEN f.[CheckSum] \n                                ELSE m.NewCheckSum \n                              END) AS CheckSum,\n                      ', __pyx_skip_dispatch=<optimized out>, __pyx_optional_args=<optimized out>) at _mssql.c:10112
#5  0x00007fd49fd5d7fc in __pyx_pf_6_mssql_15MSSQLConnection_20execute_query (__pyx_v_params=<optimized out>,
    __pyx_v_query_string=<optimized out>, __pyx_v_self=0x3700980) at _mssql.c:10225
#6  __pyx_pw_6_mssql_15MSSQLConnection_21execute_query (
    __pyx_v_self=<_mssql.MSSQLConnection at remote 0x3700980>, __pyx_args=<optimized out>, __pyx_kwds=0x0)
    at _mssql.c:10206
#7  0x00007fd4a1ce23db in __Pyx_PyObject_Call (kw=0x0, arg=<optimized out>,
    func=<built-in method execute_query of _mssql.MSSQLConnection object at remote 0x3700980>) at pymssql.c:12089
#8  __pyx_pf_7pymssql_6Cursor_12execute (__pyx_v_params=<optimized out>, __pyx_v_operation=<optimized out>,
    __pyx_v_self=0x38e59a8) at pymssql.c:6180
#9  __pyx_pw_7pymssql_6Cursor_13execute (__pyx_v_self=<pymssql.Cursor at remote 0x38e59a8>,
    __pyx_args=<optimized out>, __pyx_kwds={}) at pymssql.c:6047
#10 0x0000000000564ab2 in ext_do_call (nk=<optimized out>, na=<optimized out>, flags=<optimized out>,
    pp_stack=0x7fffaf9ff280, func=<built-in method execute of pymssql.Cursor object at remote 0x38e59a8>)
    at ../Python/ceval.c:4331
#11 PyEval_EvalFrameEx (
    f=f@entry=Frame 0x36144c0, for file /data1/projects/coreapi/staging/2.1.0/fscore/helper/ds/mssql.py, line 60, in wrapper (arg=('SELECT f.FileID,\n                              f.[Type],\n                              f.IsFol---Type <return> to continue, or q <return> to quit---
der,\n                             (CASE \n                                WHEN m.NewRelativePath IS NULL THEN f.LocalRelativePath \n                                ELSE m.NewRelativePath \n                              END) AS LocalRelativePath,\n                             (CASE \n                                WHEN m.NewFileName IS NULL THEN f.[FileName]\n                                ELSE m.NewFileName \n                              END) AS [FileName],\n                             (CASE \n                                WHEN m.NewFileSize IS NULL THEN f.FileSize \n                                ELSE m.NewFileSize \n                              END) AS FileSize,\n                             (CASE \n                                WHEN m.NewCheckSum IS NULL THEN f.[CheckSum] \n           ...(truncated), throwflag=throwflag@entry=0) at ../Python/ceval.c:2705
#12 0x0000000000556cea in PyEval_EvalCodeEx (closure=<optimized out>, defcount=<optimized out>, defs=0x0,
    kwcount=<optimized out>, kws=<optimized out>, argcount=56706240, args=<optimized out>, locals=0x0,
    globals=<optimized out>, co=<optimized out>) at ../Python/ceval.c:3253


```

```
(gdb) backtrace full
#0  0x00007fd4a5f0ba8b in raise (sig=11) at ../nptl/sysdeps/unix/sysv/linux/pt-raise.c:38
        resultvar = 0
        pid = <optimized out>
#1  <signal handler called>
No locals.
#2  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:31
No locals.
#3  0x00007fd49fd6588d in __pyx_f_6_mssql_15MSSQLConnection_get_result (__pyx_v_self=0x3700980) at _mssql.c:12153
        __pyx_v_coltype = <optimized out>
        __pyx_v_log_message = "_mssql.MSSQLConnection.get_result(): num_columns = 1\000\000\000\000@\250\221\000\000\000\000\000\200\tp\003\000\000\000\000\200\tp\003\000\000\000\000\200\tp\003\000\000\000\000p\255\221\000\000\000\000\000\200\tp\003\000\000\000\000\020\004c\003\000\000\000\000h\363\215\003\000\000\000\000`\367v\003\000\000\000\000\204\367v\003\000\000\000\000(\205֟\324\177\000\000p\255\221\000\000\000\000\000\200\tp\003\000\000\000\000\315\v\000\000\000\000\000\000\204\367v\003\000\000\000\000\001\000\000\000\000\000\000\000\220\030f\003\000\000\000\000\001\000\000\000\000\000\000"
        __pyx_v_column_names = <optimized out>
        __pyx_v_column_types = []
        __pyx_v_col = 1
        __pyx_v_column_name = 0x0
        __pyx_r = 0x0
        __pyx_t_1 = <optimized out>
        __pyx_t_2 = <optimized out>
        __pyx_t_3 = <optimized out>
        __pyx_t_4 = <optimized out>
        __pyx_t_5 = 0x0
        __pyx_t_6 = <optimized out>
        __pyx_t_7 = 1
        __pyx_t_8 = 0x0
        __pyx_t_10 = <optimized out>
        __pyx_t_11 = <optimized out>
        __pyx_lineno = 0
        __pyx_filename = 0x0
---Type <return> to continue, or q <return> to quit---
        __pyx_clineno = 0
#4  0x00007fd49fd5c8cc in __pyx_f_6_mssql_15MSSQLConnection_execute_query (__pyx_v_self=0x3700980,
    __pyx_v_query_string='SELECT f.FileID,\n                              f.[Type],\n                              f.IsFolder,\n                             (CASE \n                                WHEN m.NewRelativePath IS NULL THEN f.LocalRelativePath \n                                ELSE m.NewRelativePath \n                              END) AS LocalRelativePath,\n                             (CASE \n                                WHEN m.NewFileName IS NULL THEN f.[FileName]\n                                ELSE m.NewFileName \n                              END) AS [FileName],\n                             (CASE \n                                WHEN m.NewFileSize IS NULL THEN f.FileSize \n                                ELSE m.NewFileSize \n                              END) AS FileSize,\n                             (CASE \n                                WHEN m.NewCheckSum IS NULL THEN f.[CheckSum] \n                                ELSE m.NewCheckSum \n                              END) AS CheckSum,\n                      ', __pyx_skip_dispatch=<optimized out>, __pyx_optional_args=<optimized out>) at _mssql.c:10112
        __pyx_v_params = {'user_id': u'9243198c-272c-3a9f-87ad-88ae2833c911'}
        __pyx_r = 0x0
        __pyx_t_1 = 0x0
        __pyx_t_2 = 0x0
        __pyx_t_3 = 0x0
        __pyx_t_4 = {__pyx_n = 1, params = {'user_id': u'9243198c-272c-3a9f-87ad-88ae2833c911'}}
        __pyx_lineno = 0
        __pyx_filename = 0x0
        __pyx_clineno = 0
#5  0x00007fd49fd5d7fc in __pyx_pf_6_mssql_15MSSQLConnection_20execute_query (__pyx_v_params=<optimized out>,
    __pyx_v_query_string=<optimized out>, __pyx_v_self=0x3700980) at _mssql.c:10225
        __pyx_t_2 = {__pyx_n = 1, params = {'user_id': u'9243198c-272c-3a9f-87ad-88ae2833c911'}}
        __pyx_r = 0x0
        __pyx_t_1 = 0x0
        __pyx_lineno = 0
        __pyx_filename = 0x0
        __pyx_clineno = 0
#6  __pyx_pw_6_mssql_15MSSQLConnection_21execute_query (
    __pyx_v_self=<_mssql.MSSQLConnection at remote 0x3700980>, __pyx_args=<optimized out>, __pyx_kwds=0x0)
    at _mssql.c:10206
```

**Comment by ramiro** [comment] 2016-01-14 16:51
@pcdinh 

Please test PR #373 as it contains a fix (or rather a workaround) to the error condition as seen from pymssql.

Pending your feedback, this together with #147 (already merged) this could mean all the reported segfaults problems are solved.

Also, I'm closing this one as a duplicate of #271.

**Closed by ramiro** 2016-01-14 16:51 UTC
Labels: Blocked: Feedback Needed, bug
