### ISSUE TITLE
pymssql crashes after four hour query with ``*** Error in `python3': corrupted double-linked list: 0x00000000032e8c70 ***``

### ISSUE THREAD

**Issue by erg** [pymssql/pymssql#501] opened 2017-07-30 16:06 UTC
I'm not sure if this is a pymssql bug or a python3 bug. The chunksize is 10 (I meant to use 10k), and the file size is 28,555,223,783. Anyway, nothing should be crashing...

```python
# Pseudocode
with pymssql.connect(
    server=sever, # etc
) as db:
     for i, chunk in enumerate(pandas.read_sql(query, db, params=params, chunksize=chunksize)):
         chunk.to_hdf(...)
```

```
Traceback (most recent call last):
  File "pymssql.pyx", line 530, in pymssql.Cursor.fetchmany (pymssql.c:9010)
  File "pymssql.pyx", line 499, in pymssql.Cursor.getrow (pymssql.c:8322)
  File "_mssql.pyx", line 440, in _mssql.MSSQLRowIterator.__next__ (_mssql.c:4783)
  File "_mssql.pyx", line 1126, in _mssql.MSSQLConnection.fetch_next_row (_mssql.c:12344)
  File "_mssql.pyx", line 1586, in _mssql.check_cancel_and_raise (_mssql.c:16880)
  File "_mssql.pyx", line 1630, in _mssql.maybe_raise_MSSQLDatabaseException (_mssql.c:17524)
_mssql.MSSQLDatabaseException: (20004, b'\xe0%\xfe\x07')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sql_to_pandas.py", line 65, in <module>
    main()
  File "sql_to_pandas.py", line 61, in main
    arguments['<pandasfilename>'], verbose=True)
  File "sql_to_pandas.py", line 51, in glglive_to_pandas
    for i, chunk in enumerate(pandas.read_sql(query, glglive, params=params, chunksize=chunksize)):
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/sql.py", line 1424, in _query_iterator
    data = cursor.fetchmany(chunksize)
  File "pymssql.pyx", line 536, in pymssql.Cursor.fetchmany (pymssql.c:9185)
pymssql.OperationalError: (20004, b'\xe0%\xfe\x07')
*** Error in `python3': corrupted double-linked list: 0x00000000032e8c70 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f8da79de7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x80c71)[0x7f8da79e7c71]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f8da79eb53c]
python3[0x4e9137]
python3[0x541457]
python3[0x54146d]
python3[0x54146d]
python3(PyDict_SetItem+0x268)[0x582268]
python3(PyDict_SetItemString+0x4c)[0x587dac]
python3(PyImport_Cleanup+0x8e)[0x51adde]
python3(Py_Finalize+0x5e)[0x5fea5e]
python3(Py_Main+0x644)[0x63e9c4]
python3(main+0xe1)[0x4cfe41]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f8da7987830]
python3(_start+0x29)[0x5d5f29]
======= Memory map: ========
00400000-007a8000 r-xp 00000000 ca:01 24275                              /usr/bin/python3.5
009a8000-009aa000 r--p 003a8000 ca:01 24275                              /usr/bin/python3.5
009aa000-00a41000 rw-p 003aa000 ca:01 24275                              /usr/bin/python3.5
00a41000-00a72000 rw-p 00000000 00:00 0 
02768000-0a094000 rw-p 00000000 00:00 0                                  [heap]
7f8d88000000-7f8d88021000 rw-p 00000000 00:00 0 
7f8d88021000-7f8d8c000000 ---p 00000000 00:00 0 
...
...
...
```

**Comment by rsyring** [comment] 2017-07-31 13:19
I'm sorry, I'm going to have to close this bug report since our ability to duplicate it is nil.  If you can trace down the problem and provide an easily reproducible example, I'm happy to re-open.  But without that, I don't think any of the current maintainers would be able to pick up something like this anytime in the foreseeable future.

**Closed by rsyring** 2017-07-31 13:19 UTC
