### ISSUE TITLE
callproc replaces empty strings with NULL

### ISSUE THREAD

**Issue by d-chugunov** [pymssql/pymssql#335] opened 2015-07-07 14:48 UTC
I have the following code:
```
with pymssql.connect(server, username, password, dbname, autocommit=True) as conn:
            with conn.cursor(as_dict=True) as cursor:
                cursor.callproc("dbo.SomeProc", ("param1", "param2", "", "param4"))
```

SQL Server profiler says that SQL Server receives the following SQL query: `exec dbo.SomeProc 'param1','param2',NULL,'param4'`. As you can see, the third parameter (the empty string) is replaced with NULL. But my function cannot get NULL (empty string is OK). Why is there such convertion? I use pymsql 2.1.1 (it was installed using `pip-3.2 install pymssql`).

**Comment by rsyring** [comment] 2015-07-07 14:52
I can see where that would be frustrating.  Unfortunately, I'm not sure right-off what the solution would be.

I recommend you take this question to the mailing list: https://groups.google.com/forum/#!forum/pymssql

If this turns out to be an actual bug or feature request (i.e. not a question), then please re-open the issue.  Thanks.  :)

**Comment by ramiro** [comment] 2015-10-19 01:37
Duplicate of #243. Actually a FreeTDS (Sybase, MS dblib) stored prcedure API particularity.

**Closed by ramiro** 2015-10-19 01:37 UTC
