### ISSUE TITLE
could not locate 'clock_gettime' function required by FreeTDS

### ISSUE THREAD

**Issue by yichilin** [pymssql/pymssql#762] opened 2022-06-23 13:31 UTC
I tried to install pymssql in Dockerfile with `python:3.9-slim` base image. 
However, I got the following errors, any idea how to resolve? Thanks in advance. 

```bash
× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [6 lines of output]
    setup.py: platform.system() => Linux
    setup.py: platform.architecture() => ('64bit', '')
    setup.py: platform.libc_ver() => ('glibc', '2.31')
    setup.py: include_dirs => []
    setup.py: library_dirs => []
    setup.py: could not locate 'clock_gettime' function required by FreeTDS.
    [end of output]
```

**Comment by termim** [comment] 2022-07-02 17:37
I could not reproduce this error. Could you provide more details? What command did you run?

**Comment by pinglife80** [comment] 2022-08-27 09:00
@yichilin the same issue i have met , when i tried to  build Dockerfile  with python:3.8.13-alpine , and use command " pip install pymssql==2.2.3" ,

**Comment by angyisz** [comment] 2022-09-09 09:40
The same issue, with any recent Python in Alpine image. In setup.py compiler.has_function('clock_gettime(0,NULL)', includes=['time.h'], libraries=['rt']) is false. It should be Alpine issue, with other linux distrib not fails.

**Comment by TheophileDiot** [comment] 2022-11-09 13:36
I found a fix for this issue by following the answer here : [https://stackoverflow.com/a/45611410/12331174](https://stackoverflow.com/a/45611410/12331174)

and with this issue answer: [https://github.com/pymssql/pymssql/issues/372#issuecomment-740015317](https://github.com/pymssql/pymssql/issues/372#issuecomment-740015317)

**Closed** 2022-11-13 05:08 UTC
