### ISSUE TITLE
Pymssql 2.2.8 is missing wheel packages for Windows

### ISSUE THREAD

**Issue by MarleTangible** [pymssql/pymssql#839] opened 2023-08-01 15:55 UTC
Unable to install `pymssql` on Windows due to missing wheel packages. Normal installation fails due to missing C++ Build Tools. Current workaround is to install the prior version (2.2.7) with `pip install pymssql==2.2.7` but this might prevent some new users from discovering the package.

``` PowerShell
(.venv) PS C:\Users\MarleTangible\Documents\SampleProject> pip install pymssql
Collecting pymssql
  Using cached pymssql-2.2.8.tar.gz (171 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pymssql
  Building wheel for pymssql (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pymssql (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [34 lines of output]
      setup.py: platform.system() => Windows
      setup.py: platform.architecture() => ('64bit', 'WindowsPE')
      setup.py: include_dirs => []
      setup.py: library_dirs => []
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-310
      creating build\lib.win-amd64-cpython-310\pymssql
      copying src\pymssql\__init__.py -> build\lib.win-amd64-cpython-310\pymssql
      running build_ext
      warning: src\pymssql\_mssql.pyx:27:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src\pymssql\_mssql.pyx:28:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src\pymssql\_mssql.pyx:29:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src\pymssql\_mssql.pyx:30:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src\pymssql\_mssql.pyx:31:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src\pymssql\_mssql.pyx:32:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src\pymssql\_mssql.pyx:35:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src\pymssql\_mssql.pyx:36:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src\pymssql\_mssql.pyx:38:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src\pymssql\_mssql.pyx:82:0: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src\pymssql\_mssql.pyx:230:0: The 'DEF' statement is deprecated and will be removed in a future Cython version. Consider using global variables, constants, and in-place literals instead. See https://github.com/cython/cython/issues/4310
      warning: src\pymssql\_mssql.pyx:264:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src\pymssql\_mssql.pyx:333:4: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src\pymssql\_mssql.pyx:831:8: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src\pymssql\_mssql.pyx:919:8: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src\pymssql\_mssql.pyx:1005:12: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src\pymssql\_mssql.pyx:1379:16: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      warning: src\pymssql\_mssql.pyx:1713:8: The 'IF' statement is deprecated and will be removed in a future Cython version. Consider using runtime conditions or C macros instead. See https://github.com/cython/cython/issues/4310
      Compiling src\pymssql\_mssql.pyx because it changed.
      [1/1] Cythonizing src\pymssql\_mssql.pyx
      building 'pymssql._mssql' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pymssql
Failed to build pymssql
ERROR: Could not build wheels for pymssql, which is required to install pyproject.toml-based projects
(.venv) PS C:\Users\MarleTangible\Documents\SampleProject>
```

**Comment by itopaloglu83** [comment] 2023-08-01 22:51
Looks like the GitHub workflow for Windows failed for some reason 2 days ago.
Could someone manually trigger it for the v2.2.8 tag? @termim

**Comment by PrimozGodec** [comment] 2023-08-03 12:06
Please provide wheels for Windows. It is breaking multiple packages using PYMSSQL.

**Comment by termim** [comment] 2023-08-03 22:37
@PrimozGodec you can use `--only-binary` pip  requirements option and you project will never break in case only source is available.

**Comment by PrimozGodec** [comment] 2023-08-07 14:07
@termim, the problem is that Orange data mining users, who install this package, usually do not have the proper compilers to build a package (and they are not computer scientists to have enough knowledge to know how to install compilers). They would benefit a lot from wheels. I am open to help with making this work. I noticed that Windows tests/builds fail (probably due to changes in Cython). Can you please enable build runs in my PR so I can investigate further https://github.com/pymssql/pymssql/pull/840.

**Comment by termim** [comment] 2023-08-09 00:01
@PrimozGodec I've enabled build for you PR, but you can run builds in your fork any time you want without any approval.

**Comment by MarleTangible** [comment] 2023-08-09 10:13
@PrimozGodec thank you for working on solving this issue. Do you see a path forward or is it more like a trial-and-error kind?

**Comment by MarleTangible** [comment] 2023-08-14 11:25
I was checking the OpenSSL versions to see what changed but apparently this issue is caused by the OpenSSL version `choco` package manager has. Choco version history shows that on May 31st they switched from v1.1.1 to v3.1.1. I think updating the `test_windows.yml` as below would resolve the issue for now. But the support of OpenSSL 3 is another issue of its own.

From:
``` YAML
      run: choco install openssl --forcex86
```
To:
``` YAML
      run: choco install openssl --forcex86 --version=1.1.1.2100
```

**Comment by PrimozGodec** [comment] 2023-08-14 13:51
@MarleTangible, it is exactly what you wrote, and I am testing it in #840. I think we will need to keep the older version here until it is fixed. Here is also the test run: https://github.com/PrimozGodec/pymssql/actions/runs/5856212257.

After some trying, I still don't know why we get `LINK: fatal error LNK1181: cannot open input file 'libssl_static.lib'` in x64 build (I tried with an older version of OpenSSL, but it always fails. The last successful run on this repo was at the end of March, but the log expired, so it is impossible to compare. I can do some more trying tomorrow.

**Comment by PrimozGodec** [comment] 2023-08-15 11:12
I pinned it to 1.1.1.2000 which is most probably the version that was used in march when the build didn't fail https://github.com/PrimozGodec/pymssql/actions/runs/5865293272/job/15901922167. It is still the same.

**Comment by PrimozGodec** [comment] 2023-08-15 11:14
It may be connected to https://github.com/openssl/openssl/issues/12358 but this was reported in 2020 already and the build was still working this year.

**Comment by PrimozGodec** [comment] 2023-08-15 14:24
I tried with older Cython. I even went to a version which was most likely used in the March working build, but sadly it is still failing https://github.com/PrimozGodec/pymssql/actions/runs/5867747947/job/15909082836

**Comment by PrimozGodec** [comment] 2023-08-16 08:03
I found an issue (it seems the path where Choco installs OpenSLL is different now). It should be fixed with: https://github.com/pymssql/pymssql/pull/840

**Comment by termim** [comment] 2023-08-17 21:57
2.2.8 windows wheels are on PyPI already.

**Closed by termim** 2023-08-17 21:57 UTC
