### ISSUE TITLE
time type is not supported

### ISSUE THREAD

**Issue by pymssql-issue-migrator** [pymssql/pymssql#107] opened 2013-09-24 05:21 UTC
_From [maxim.ye...@gmail.com](https://code.google.com/u/105886620856644591867/) on November 15, 2012 05:43:33_

pymssql supports datetime and date types, but not time for some reason.

Attached is a patch for pymssql-2.0.0b1-dev-20111019 that adds time type support.

**Attachment:** [time.patch](http://code.google.com/p/pymssql/issues/detail?id=103)

_Original issue: http://code.google.com/p/pymssql/issues/detail?id=103_

**Comment by ramiro** [comment] 2015-10-19 03:50
Closing as duplicate of #331 that although is newer, has a more complete and up to date patch.

**Closed by ramiro** 2015-10-19 03:50 UTC
Labels: Blocked: FreeTDS
