### ISSUE TITLE
Segfault on network partitioning

### ISSUE THREAD

**Issue by roginski** [pymssql/pymssql#271] opened 2014-08-21 08:30 UTC
Hello.

Have an easily-reproduced segfault here. Run this script:
```
import pymssql
import time
import logging

def connect():
	return pymssql.connect(
		server='*****', 
		user='*****',
		password='*****',
		database='*****', 
		timeout=1)

connection = connect()
while 1:
	try:
		connection.cursor().execute('select * from MyTable')
	except pymssql.DatabaseError as e:
		logging.exception(e)
		time.sleep(1)
		continue

	print 'ok'
	time.sleep(1)
```
Then turn off network on client machine, see this:
```
ok
ok
ok
ERROR:root:(20003, 'DB-Lib error message 20003, severity 6:\nAdaptive Server connection timed out\n')
Traceback (most recent call last):
  File "./testdb.py", line 25, in <module>
    connection.cursor().execute('select * from Tasks')
  File "pymssql.pyx", line 384, in pymssql.Cursor.execute (pymssql.c:4289)
OperationalError: (20003, 'DB-Lib error message 20003, severity 6:\nAdaptive Server connection timed out\n')
Segmentation fault
```
Looks like segfault caused by using the connection after connection failure. I could live with it if I knew how to work around that. Reconnect on each OperationalError? That's not pretty because it's not only network partitioning that causes OperationalError but many other things according to sources. Any ideas?

**Comment by DavidRueter** [comment] 2015-12-31 15:11
Any update on this issue?  I am having similar problems.

**Comment by rsyring** [comment] 2015-12-31 15:58
@DavidRueter no, sorry.  pymssql has a pretty small volunteer team.  If we make any progress, the issue will get updated.

**Comment by DavidRueter** [comment] 2015-12-31 18:36
Thanks, Randy.  I’m not opposed to digging in to take a look.  Do you have any notes or overview of how TDS exceptions are supposed to be handled and/or how pymssql timeouts are implemented?

 

Relatedly, do you have any thoughts on the best way to gracefully cancel a long-running query?

 

Or is it best to just roll up my sleeves and dig into the source?

**Comment by rsyring** [comment] 2015-12-31 19:27
I'd suggest posting any questions you have and/or request for guidance to the FreeTDS mailing list.  How to solve this problem may already be known by others who use FreeTDS and it's just a matter of implementation in pymssql.

**Comment by DavidRueter** [comment] 2016-01-01 16:32
I think there is some good news:  FreeTDS was updated 13 days ago with what seems to be a fix for exactly this problem:

https://github.com/FreeTDS/freetds/commit/420141cc10a8f0110e1c6773d3487c4b085af9a2

The bug in FreeTDS seems to mean that if the TCP/IP socket went dead there would be a segfault.

Presumably using an updated version of FreeTDS will solve the problem.

**Comment by ramiro** [comment] 2016-01-01 17:21
> I think there is some good news: FreeTDS was updated 13 days ago with what seems to be a fix for exactly this problem:
> 
> FreeTDS/freetds@420141c
> 
> The bug in FreeTDS seems to mean that if the TCP/IP socket went dead there would be a segfault.
> 
> Presumably using an updated version of FreeTDS will solve the problem.

That's what I thougt when I saw that commit.

Unfortunately , from my experiments with the a checkout of the latest FreeTDS branch 0.95 (which also included the fix) a  segmentation fault still happens.

This was part of an effort I made  a cople of days ago which took me almost a full working day

No success so far.

**Comment by jcrudy** [comment] 2016-01-01 19:38
I am using pymssql version 2.1.1 and freetds version 0.91-5 (according to synaptic) on Linux Mint version 17.2.  I've also experienced segfaults (or what seemed like segfaults - python program suddenly terminates with no exception raised) when testing an application that needs to recover from disconnects from the SQL server.  Basically, this application performs a query that returns a huge number of rows, then iterates through the rows using a cursor (via SQLAlchemy via pymssql).  If the connection to the server is lost while iterating through the rows, it tries again with a new query that starts after whatever the last successfully processed row was.  These queries are executed using a `sqlalchemy.engine.Engine`, which maintains a pool of connections to the database server (via pymssql).  Testing this system with an unrealistically high rate of disconnects, I started to see this segfault problem and traced it back to the point where the engine executes the query.  That eventually led me to this bug report.

The main reason I'm reporting this here is to share a workaround.  This applies if you use SQLAlchemy and don't actually need to reuse connections.  When constructing an engine with `create_engine`, use  `poolclass=NullPool`, like this:

    from sqlalchemy.engine import create_engine
    from sqlalchemy.pool import NullPool
    
    engine = create_engine(db_url, poolclass=NullPool)

This causes SQLAlchemy to not reuse connections, which for me solved the segfault problem.

**Comment by DavidRueter** [comment] 2016-01-01 20:41
I just did a search for calls to dbperror() through all FreeTDS source files, and found a number of other places in dblib.c where it is called with dbperror(NULL,...) instead of dbperror(dbproc,...)  I have not yet looked closer, but I suspect that perhaps these also result in the segfault?

@jcrudy thanks for your feedback.  My scenario is somewhat different, but I definitely see the segfault when the TCP/IP connection to the SQL Server is lost (but not when the logical connection is dropped by issuing a KILL xxx on the server to kill the connection's SPID).  This happens even when only a single SQL connection is in use, and even when it is not retrieving a large resultset.

I am not yet set up to build FreeTDS (or pymssql).  I guess I will need to get my dev environment set up to do these builds before I go much further on this.

**Comment by jcrudy** [comment] 2016-01-02 19:28
I turns out my NullPool workaround hasn't actually eliminated all segfaults.  It just reduced their frequency quite a lot.  Also, I have a clue.  This time, before my program segfaulted (or seemed to, at least), I got the following on stderr:

    python: read.c:194: tds_get_string: Assertion `string_len >= 0 && dest_size >= 0' failed.

**Comment by ramiro** [comment] 2016-01-03 16:24
Update:

the next logical thing to do seemed trying to know if this a FreeTDS problem. So I created a .c  program which tries to perform the same FreeTDS dblib API calls in a loop as the ones called by the Python scripts that use pymssql posted to this issue and to the #147 PR.

This is it: https://gist.github.com/ramiro/7ae90c01041f5d6f3213

I was unable to reproduce the segmentation faults in presence of network partition.

Next step was to perform something similar but using _mssql instead of pymssql: https://gist.github.com/ramiro/8c2c4e58fdd9aac030b0

with this script I was able to reproduce the segfaults.

But there is good news:

Once I:

1. Use FreeTDS from latest fixes-only post-0.95 branch (https://github.com/FreeTDS/freetds/commits/Branch-0_95)
2. Apply @msabramo 's fix from PR #147 

I can't  reproduce the problem when using the _mssql API, unfortunately segfaults still happen when using pymssql.

So it seems Marc work is an advancement in the right direction.

Please test the three programs/scripts above and report back your experiences.

**Comment by ramiro** [comment] 2016-01-03 16:37
Forgot to link the pymssql script URL: https://gist.github.com/ramiro/abae68b610d92384a73a

How to use the scripts:

`issue271.py` (pymssql API):
1. Edit it to set your DB server ID addres, user name, password and database.
2. Run it: `$ python issue271.py`
3. Interrupt the connection to the server somehow

`issue271_mssql.py` (_mssql API):
1. Edit it to set your DB server ID addres, user name, password and database.
2. Run it: `$ python issue271_mssql.py`
3. Interrupt the connection to the server somehow

`issue271.c` (FreeDTS dblib API):
1. Compile it (for example): `$ LIBRARY_PATH=${PWD}/../../lib CPATH=${PWD}/../../include cc -Wall issue271.c -lsybdb -o issue271`
2. Run it: `$ ./issue271  -S xxx.xxx.xxx.xxx -D dbname -U username -P mypassword "SELECT @@version"`
3. Interrupt the connection to the server somehow


Regarding step 3. after a while, instead of having to turn my WiFi connection on and off to provoke the networkk partition I opted for using the tcpkill program (par of ther dnsniff suite):

```
$ sudo tcpkill -i wlan0 "dst host xxx.xxx.xxx.xxx and port 1433
```

**Comment by ramiro** [comment] 2016-01-14 16:49
@roginski @DavidRueter @jcrudy 

Please test PR #373 as it contains a fix (or rather a workaround) to the error condition as seen from pymssql.

Pending your feedback, this together with #147 (already merged) this could mean all the reported segfaults problems are solved.

**Closed** 2016-01-23 15:36 UTC
Labels: bug
