### ISSUE TITLE
Segfault during network disconnect

### ISSUE THREAD

**Issue by eusebeus** [pymssql/pymssql#353] opened 2015-11-04 19:26 UTC
Reposing from https://groups.google.com/forum/#!topic/pymssql/IWg48wjrNxA

Hi All,

We've recently started using pymssql 2.1.1 with antipool (antiorm) and we've run into a segmentation fault when there's is a network disconnect.

The repro below illustrates the issue (without antipool).  I'm running pymssql 2.1.1, Python 2.7.6, and freetds 0.91-5 on Ubuntu 14.04.

Any ideas on a fix or work-around?

Thanks!

1. Ensure network connection is live and start running the following script.

```
import pymssql
import time

with pymssql.connect(server='myserver',
                     database='mydb',
                     user='myuser',
                     password='mypassword',
                     timeout=5) as conn:
    while True:
        try:
            with conn.cursor(as_dict = False) as cur:
                cur.execute('SELECT @@VERSION')
                row = cur.fetchone()
                print('OK', row)
        except Exception as e:
            print('*** ERROR', str(e))

        time.sleep(1)
```

2. After a few successful execute calls disconnect your network connection.

Expected: Graceful errors (exceptions) from the execute call for infinity
Actual: One of the following errors and then core dump.

```
('*** 1 ERROR', "(20003, 'DB-Lib error message 20003, severity 6:\\nAdaptive Server connection timed out\\n')")
Segmentation fault: 11
```

**Comment by ramiro** [comment] 2015-11-04 19:37
See also #147, #261, #271

**Comment by eusebeus** [comment] 2015-11-05 17:13
Thanks @ramiro ! Gosh, I feel like a noob for posting a dupe. (I did try looking / Googling for similar issues, though.) Should I resolve this as such?

**Comment by ramiro** [comment] 2015-11-06 12:16
I had a very superficial look at this and these issues. Now I see this looks very similar to #271. I'll close ad a duplicate of it.

**Closed by ramiro** 2015-11-06 12:16 UTC

**Comment by ramiro** [comment] 2016-01-14 16:50
@eusebeus 

Please test PR #373 as it contains a fix (or rather a workaround) to the error condition as seen from pymssql.

Pending your feedback, this together with #147 (already merged) this could mean all the reported segfaults problems are solved.
