### ISSUE TITLE
Inconsistent handling of None value in parameter substitution

### ISSUE THREAD

**Issue by invokermain** [pymssql/pymssql#696] opened 2021-02-04 12:51 UTC
**Describe the bug**
Inconsistent handling of None parameter when performing parameter substitution.

**To Reproduce**
```python
>>> import pymssql as sql
>>> sql._mssql.substitute_params("%s", None)
'%s'
>>>sql._mssql.substitute_params("%s", (None, ))
b'NULL'
```

**Expected behavior**
In both these cases I would expect `b'NULL'` to be returned.

**Current Behavior**
Passing none to `substitute_params` is ignored.

**Context (Environment)**
```python
>>> sql.__version__
'2.1.5'
>>> sql.get_dbversion()
b'freetds v1.2.4'
```

**Additional context**
I imagine the issue is because there's no distinction between `None` because parameters were not passed or `None` explicitly passed.

If this is not a bug the documentation around this should be improved:

[Docs](https://pymssql.readthedocs.io/en/latest/ref/pymssql.html#cusor-object-methods) state: "operation is a string and params, if specified, is a simple value, a tuple, a dict, or None." This implies that passing None as a single Parameter is valid.

**Comment by termim** [comment] 2021-02-04 17:29
Please see [DBAPI2](https://www.python.org/dev/peps/pep-0249/#id15) definition of parameters: _"Parameters may be provided as **sequence or mapping** ..."_.
In your example _None_ means no parameters, so the original string is returned without any substitution. If you'll use some non Null value then it will be used:

```
>>> sql._mssql.substitute_params("%s", 0)
b'0'
>>> 
```
DBAPI2 is not very clear here, it uses _**may**_, leaving some freedom for the special case when there is only one placeholder ...
So, this is not a bug, closing.

**Closed by termim** 2021-02-04 17:29 UTC

**Comment by invokermain** [comment] 2021-02-04 18:44
Hey thanks for the quick reply, I guessed that this was not really a bug, but this behaviour is also not really clear in the documentation.

The docs state "params, if specified, is a simple value, a tuple, a dict, or None". Is `None` not a simple value? Should it not say "params, if specified ... cannot be None" as this will be ignored?

**Comment by termim** [comment] 2021-02-04 20:27
Please read further:

> If you call execute() with one argument, the % sign loses its special meaning, so you can use it as usual in your query string, for example in LIKE operator.

**Comment by invokermain** [comment] 2021-02-04 20:35
That's irrelevant to this issue, `execute("...", None)` is two arguments, also I haven't mentioned `execute()` in this issue. I am trying to suggest that the docs could be more explicit around this behaviour (`substitute_params` isn't even documented), but clearly we disagree.

**Comment by termim** [comment] 2021-02-04 21:00
Function `substitute_params` is not a part of the official DBAPI or pymssql API, it is internal implementation detail and because of that it is not documented. IMHO there is no issue here.
